### ISSUE TITLE
Abnormal zoom

### ISSUE THREAD

**Issue by GrimPixel** [noobj2/Anki_Change_Interface_Font#5] opened 2022-02-25 18:24 UTC
After opening decks and returning to the list of decks, the font become sometimes tiny and sometimes very large.
    
    Anki 2.1.50 (3564ece6) Python 3.10.2 Qt 5.15.2 PyQt 5.15.6
    Platform: Linux
    Flags: frz=False ao=True sv=2
    Add-ons, last update check: 2022-02-25 16:14:28
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Change Interface Font ['1431333984', 2021-08-27T01:36, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1431333984
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Add Hyperlink ['318752047', 2022-02-08T23:21, 'None', '']
    Add Table ['1237621971', 2021-12-05T20:27, 'None', '']
    Adjust Sound Volume ['2123044452', 2021-05-05T12:24, 'None', '']
    Advanced Answer Sounds ['1167194350', 2021-12-30T05:41, 'None', mod]
    Advanced Browser ['874215009', 2022-01-30T23:07, 'None', '']
    Advanced Copy Fields ['1898445115', 2019-05-03T19:46, 'None', '']
    Advanced Review Bottom Bar ['1136455830', 2022-02-13T07:57, 'None', mod]
    Allows empty first field during adding and import ['46741504', 2021-10-17T22:27, 'None', '']
    Anki Simulator ['817108664', 2021-08-07T20:24, 'None', '']
    Anki Speed Limit ['395996975', 2021-03-23T13:03, 'None', '']
    Anki Zoom ['538879081', 2020-04-04T01:20, 'v1.1.3', mod]
    AnkiConnect ['2055492159', 2022-02-19T19:11, 'None', '']
    AnkiWebView Inspector ['31746032', 2019-05-02T23:43, 'None', '']
    Ankimote - remote to control Anki from your phone ['149004221', 2021-08-11T17:57, 'None', '']
    Batch Editing ['291119185', 2019-06-02T19:47, 'None', '']
    BetterSearch ['1052724801', 2022-01-25T22:25, 'None', '']
    BiDi Tools ['281067366', 2022-01-14T01:41, 'None', '']
    Browser Resizer ['1435775540', 2021-08-01T22:11, 'None', '']
    Browser TableEditor side-by-side horizontal split ['831846358', 2022-01-25T22:11, 'None', '']
    ColorCoding ['2113325087', 2022-02-02T22:27, 'None', '']
    Correct Answers Graph ['993120073', 2020-03-24T12:57, 'None', '']
    Countdown To Events and Exams ['1143540799', 2021-03-13T20:40, 'None', '']
    Custom Background Image and Gear Icon ['1210908941', 2022-02-24T23:21, 'None', '']
    Deck Browser CSS ['153779542', 2021-12-21T08:29, 'None', '']
    Delay siblings ['1369579727', 2020-08-27T13:08, 'None', '']
    Directly review without going through overview page ['1024346707', 2019-11-07T08:36, 'None', '']
    Edit Field During Review ['1020366288', 2020-10-07T13:22, 'None', '']
    Editor Live Preview ['1960039667', 2021-10-09T05:06, 'None', '']
    Enhanced Cloze for Anki 21 ['1990296174', 2022-02-13T21:19, 'None', '']
    Extended Heatmap Updated January 2022 ['2011818092', 2022-02-02T02:28, 'None', '']
    Extended deck menu ['576235837', 2022-02-23T23:57, 'None', '']
    Fastbar- with nightmode support ['46611790', 2022-02-04T21:02, 'None', '']
    Field AutoComplete ['511710206', 2022-02-25T10:03, 'None', '']
    Fill the blanks - Multiple typecloze support ['1933645497', 2021-08-05T20:38, 'None', '']
    Flag label ['671965183', 2020-05-14T12:05, 'None', '']
    Fluent Forever - Open Websites ['143682703', 2019-12-22T17:22, 'None', '']
    Highlight Color Shortcut ['1178291236', 2021-04-01T17:42, 'None', '']
    Highlight Search Results in the Browser ['225180905', 2021-03-10T17:06, 'None', '']
    Image Editor ['307397307', 2021-12-19T11:58, 'None', '']
    Image Style Editor ['1593969147', 2021-12-17T07:01, 'None', mod]
    Learn now Button ['1021636467', 2021-10-15T19:21, 'None', '']
    Load Balanced Scheduler ['208879074', 2018-10-05T01:06, 'None', '']
    Markdown and KaTeX Support ['1087328706', 2022-02-10T16:44, 'None', '']
    Media Import ['1531997860', 2018-07-14T13:32, 'None', '']
    Merge Notes ['1425504015', 2022-01-21T11:48, 'None', '']
    Mindmap from tag hierarchy ['965278890', 2022-02-02T20:19, 'None', '']
    Mini Format Pack ['295889520', 2018-07-24T18:45, 'None', '']
    Minimize to tray ['85158043', 2021-12-13T16:59, 'None', '']
    More Overview Stats 21 ['738807903', 2021-07-30T20:13, 'None', '']
    Multiple Choice for Anki ['1566095810', 2021-03-18T17:50, 'None', '']
    Number of Decks ['1358364553', 2019-12-11T19:01, 'None', '']
    Numeric Keypad Remapping  ease bugs fixed ['653807651', 2022-01-07T14:15, 'None', '']
    Open linked pdf docx epub audiovideo etc in external Program ['879473266', 2022-02-19T20:37, 'None', '']
    Opening the same window multiple time ['354407385', 2020-05-16T01:59, 'None', '']
    Paste Images As WebP ['1151815987', 2022-02-11T21:40, 'None', mod]
    Preview Slideshow ['90397199', 2021-08-06T08:42, 'None', '']
    Progress Bar cards done cards left secondscard time spentleft and ETA ['1097423555', 2021-11-30T05:45, 'None', '']
    Progress Graphs and Stats for Learned and Matured Cards ['266436365', 2020-03-29T07:26, 'None', '']
    ReColor ['688199788', 2022-02-25T10:10, '1.5', mod]
    Refocus Card when Reviewing 21 ['1642550423', 2018-09-19T15:14, 'None', '']
    Remaining time for Anki 21 ['1508357010', 2020-12-13T14:14, '20.12.13i151', '']
    Removes Empty Note Types for 21 ['530953383', 2019-06-12T15:11, 'None', '']
    Rendered Browser ['993394845', 2020-12-20T21:48, 'None', '']
    Replay buttons on card ['498789867', 2017-11-20T12:38, 'None', '']
    Reset Custom Study Limit Increases ['738867649', 2021-10-20T01:17, 'None', '']
    Reset Ease ['947935257', 2020-12-27T14:59, 'None', '']
    Ruzu Pop-ups ['1736169259', 2021-03-08T18:00, 'v0.0.2', mod]
    See Previous Card Ratings in Reviewer ['1906641654', 2021-08-19T22:32, 'None', '']
    Special Fields ['1102281552', 2022-02-23T17:27, 'None', '']
    Statistics for Note Types Card Types and Tags ['16703369', 2020-07-20T03:11, 'None', '']
    Straight Reward ['957961234', 2021-01-11T12:37, 'None', '']
    Tab Indentation ['544286375', 2022-01-21T16:42, 'None', '']
    Time per revised card graph ['1703703955', 2021-01-27T00:12, 'None', '']
    Tippy Tooltips ['1840818335', 2022-01-19T17:47, 'None', '']
    True Retention by Card Maturity Simplified ['1779060522', 2020-06-28T14:45, 'None', '']
    Word Shuffler - Sentences randomizer ['1190756458', 2021-03-30T22:45, 'None', '']
    add-on dialog searchfilter bar ['561945101', 2021-12-05T20:28, 'None', '']
    extended editor for field for tables searchreplace ['805891399', 2021-12-06T14:59, 'None', '']
    extended html editor for fields and card templates with some versioning ['1043915942', 2021-12-10T23:27, 'None', '']
    link Cards Notes and Preview them in extra window ['1423933177', 2021-12-07T15:51, 'None', '']

**Comment by noobj2** [comment] 2022-02-25 21:40
Hey. I'm on windows and tried to reproduce this bug.
Downloaded both anki 2.1.50 qt6 and qt5 version. but couldn't reproduce this bug on any of those.
Maybe it's something with python 3.10 that your version of anki uses? the versions that I downloaded use python 3.9

Hopefully when anki 2.1.50 stable version gets released I'll be able to reproduce this bug and fix it. But until then, I don't know what causes this and if I don't know what causes it, I can't fix it -_- Sorry

**Comment by GrimPixel** [comment] 2022-02-26 06:50
I opened many decks one by one, each time I change the zoom. After some clicks, it looks like this now
![zoom](https://user-images.githubusercontent.com/39795763/155833523-58f181e8-9333-4f9b-b0a1-b68bda48e3a4.png)
![zoom2](https://user-images.githubusercontent.com/39795763/155833654-c24368e0-2a89-417a-afba-bc59aa592bae.png)
.

**Comment by noobj2** [comment] 2022-02-27 12:07
I thought it just happens on its own by opening a deck and closing and returning to decks screen.
on my pc it happens when I zoom in or zoom out, and then press shortcut "D" (or click on the "decks" on the top bar). and it's not an abnormal zoom, it just repeats the last command (zooms in or out once more).
is it the same on your device?

**Comment by noobj2** [comment] 2023-07-20 15:31
alright, I tested this again on anki 2.1.65 and it's not happening anymore.
The issue wasn't cause by change interface add-on in the first place. It was just a zoom issue.
if it was caused by change interface add-on, the top and bottom bar would have had  this issue.

**Closed as completed by noobj2** 2023-07-20 15:31 UTC
